apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: loki
  namespace: default
spec:
  interval: 15m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmReleasegateway.basicAuth.enabled
metadata:
  name: loki
  namespace: default
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki
      version: 5.39.0
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: default
  interval: 15m
  timeout: 5m
values:
  gateway:
    basicAuth:
      enabled: true

#  values:
#    write:
#      persistence:
#        storageClass: pd-for-loki
#    read:
#      persistence:
#        storageClass: pd-for-loki
#    backend:
#      persistence:
#        storageClass: pd-for-loki
#    singleBinary:
#      persistence:
#        storageClass: pd-for-loki

