apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: default
spec:
  interval: 3m0s
  path: ./grafana
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: default
spec:
  interval: 3m0s
  path: ./prometheus
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
