apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: sidecar-configmap-prom
  labels:
    grafana_my_label: "1"
data:
  config-datasourceforgrafana.yaml: |-
      apiVersion: 1
      datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.default.svc.cluster.local
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki-gateway.default:3100
        access: proxy
        isDefault: false
