apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: 25.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: default
  interval: 15m
  timeout: 5m
  values:
    server:
      persistentVolume:
        enabled: false  
    alertmanager:
      persistentVolume:
        enabled: false 
