apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: prometheus
      version: 25.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: default
  interval: 15m
  timeout: 5m
  values:
    server:
      persistentVolume:
        enabled: false  
    alertmanager:
      persistentVolume:
        enabled: false 
