apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: default
spec:
  interval: 15m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: default
spec:
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: 7.0.11
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: default
  interval: 15m
  timeout: 5m
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      rules:
      - host: grafana2.mari1327.pp.ua
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server.default.svc:80
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            url: http://loki-gateway.default.svc:3100
            access: proxy
            isDefault: false
    dashboards:
      default:
        prometheus-stats:
          gnetId: 2
          revision: 2
          datasource: Prometheus
      my-dashboard:
        url: https://github.com/rfmoz/grafana-dashboards/blob/master/prometheus/node-exporter-full.json
