datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus.mari1327.pp.ua:31608 
    access: proxy
    isDefault: true
  - name: Loki
    type: loki
    url: http://loki.default.svc:3100
    access: proxy

dashboards:
  default:
    - name: Prometheus Overview
      file: full.json  

  loki:
    - name: Loki
      file: loki.json  
