apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx
  namespace: default
spec:
  interval: 15m
  url: https://helm.nginx.com/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx-ingress
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: nginx
        namespace: default
  interval: 15m
  timeout: 5m
  values:
    ingress:
      enabled: true
      ingressClassName: nginx-ingress
      rules:
      - host: grafana2.mari1327.pp.ua
        http:
          paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: heml-app-service
                port:
                  number: 3000
      
