apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: promtail
  namespace: default
spec:
  interval: 15m
  url: https://github.com/grafana/helm-charts/tree/main/charts/promtail
