apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: promtail
  namespace: default
spec:
  interval: 15m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana/promtail
      version: '6.15.3'
      sourceRef:
        kind: HelmRepository
        name: promtail
        namespace: default
      interval: 1m
